---

nginx_package_deps:
  - libpcre3-dev
  - zlib1g-dev 
  - libgcrypt11-dev

nginx_pkg: nginx-1.8.1

nginx_pkg_tar: "{{nginx_pkg}}.tar.gz"

nginx_release_url: http://nginx.org/download/{{nginx_pkg_tar}}

nginx_conf_dir: /usr/local/nginx/conf

nginx_basic_auth_file_name: .htpasswd

nginx_proxy_port: 4080

nginx_aaad_port: 8888